### ISSUE TITLE
create mastodon weblet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#1]
this weblet should have 3 tabs 
- credentials
  - [x] mnemonics 
    - [x] hidden field by default
    - [x] validate the mnemonics if it has a twin on the grid
    - [x] use session storage to keep this mnemonic
    - [x] show QR code for transferring tokens to the account once it's validated on the grid
    - [x] add an option to create an account for the user
  - [x] #2
    - [x] if it's not provided, ask the user to provide it or generate one for him (add a button for sshkey generation)
    - [x] store this sshkey on a metadata key on the blockchain
    - [x] load this key from the blockchain(from the metadata key) once the user provide the mnemonics
    - [x] add validation for this field
- basic
  - [x] select the region to deploy on
  - [x] checkbox for certified or not
  - [x] use only one size (100 GB SSD, 4 GB memory) (this should be hidden)
  - [ ] show the price of this deployment and say it's an estimate
- advanced
  - [x] custom resources selection
  - [x] farm selector (deploy on a certain farm id)
  - [x] optional public ip
  - [x] gateway selector
  - [x] admin credentials 
  - [x] smtp server 

### Checks
- [x] Check the node is reachable once you click deploy before starting the deployment

**Comment by sasha-astiadi** [comment]
[@https://github.com/threefoldtech/www-mastodon/issues/3](https://github.com/threefoldtech/www-mastodon/issues/3)

**Comment by sasha-astiadi** [comment]
https://www.figma.com/file/KhU2r4URXL8MBfF2TUs3NS/Mastodon?t=YP4qrirZG5fm93N9-1
