### ISSUE TITLE
Checking the status of a node takes too much time

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#109]
### Description

Checking the status of a node takes too much time. i takes around a minute to check the status of a node.

[Get Mastodon (33).webm](https://user-images.githubusercontent.com/101194226/206514219-dfb624e2-4022-4d39-bd1f-ab66ed9d9a00.webm)

**Comment by mohamedamer453** [comment]
The issue is still valid. as seen below it took almost 2 mins for the first node to check whether it's online or not. and for the second node it also took more than a minute to check

[Get Mastodon (39).webm](https://user-images.githubusercontent.com/101194226/208293386-a4776468-be95-4959-91c6-decd6fe02b68.webm)

**Comment by AhmedHanafy725** [comment]
fixed in the grid client, but the instance needs to be updated

**Comment by AhmedHanafy725** [comment]
@Mahmoud-Emad Please update the issue after updating the instance

**Comment by Mahmoud-Emad** [comment]
@AhmedHanafy725 
The instance should be updated now

**Comment by mohamedamer453** [comment]
> @AhmedHanafy725 The instance should be updated now

Tested a couple of different nodes after the instance was updated, but it still take around 1 min.

[Get Mastodon (42).webm](https://user-images.githubusercontent.com/101194226/209130571-9936c220-d255-4f34-ad27-b72622c788a8.webm)

[Get Mastodon (43).webm](https://user-images.githubusercontent.com/101194226/209130622-f3a75b41-4a42-4e3b-bb1f-188938b85271.webm)

**Comment by MohamedElmdary** [comment]
@mohamedamer453 Should be fixed https://github.com/threefoldtech/www-mastodon/pull/137

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

By checking the same 2 nodes the time was cut by more than half and now it only takes around 20 seconds to check the status of the node.

[Get Mastodon (44).webm](https://user-images.githubusercontent.com/101194226/209147071-996352c8-103c-4d9f-92cc-35be6f41ab4e.webm)

[Get Mastodon (45).webm](https://user-images.githubusercontent.com/101194226/209147122-0dc581cd-3227-436f-aae7-ebe2f66a3d29.webm)
