### ISSUE TITLE
UX: Improve calcPrice

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/www-mastodon#118]
![image](https://user-images.githubusercontent.com/31689104/206997284-81752554-5803-42c0-95c0-a58525b1dd79.png)
*Suggest*: Show only first line & add link to discount (**Learn More**)

**Comment by samtaggart** [comment]
Hmmm, let's go with:

Based on your specifications and TFChain TFT balance, your deployment cost is 9.04 USD/Month.
[Learn how to unlock discounts](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels)

cc: @MohamedElmdary

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io

The section for the deployment price and discounts was improved with the same format mentioned above. and the `Learn how to unlock discounts.` link redirects to https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels

![image](https://user-images.githubusercontent.com/101194226/208288859-74ccfb00-db83-4105-a26a-3c7aaa612dd3.png)
