### ISSUE TITLE
Show a message after successful deployment

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#12]
the current behavior just stays on the last log message
![image](https://user-images.githubusercontent.com/41957921/203859841-85faab81-3c30-4317-a0a2-b372f9d3971c.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps to produce:**

1. go to weblets
2. go to mastodon
3. deploy a mastodon
4. wait for deployment to complete

![Screenshot from 2022-11-29 15-17-59](https://user-images.githubusercontent.com/110984055/204539438-59d7a7c6-9677-4461-be84-06c4abc7df6e.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The successful deployment message was added instead of showing the last log message.

![image](https://user-images.githubusercontent.com/101194226/204542983-1a017274-91cf-4331-aa52-37480d534c5c.png)
