### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/www-mastodon#121]
## Updates
- [x] Add *info* (icon) to **Basic** checkbox
- [x] Remove last 3 regions

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

Info icons were added to both options in the Basic tab.

![image](https://user-images.githubusercontent.com/101194226/208291398-85a9105f-262b-4ffa-9c91-d2f96c1b8d52.png)

![image](https://user-images.githubusercontent.com/101194226/208291269-f49150cc-9935-48e5-a63f-9f0ced6c0e8a.png)

![image](https://user-images.githubusercontent.com/101194226/208291294-264e8dac-4cca-4f1c-996e-023c8039972c.png)

And the mentioned Regions were removed from the Region list.

![image](https://user-images.githubusercontent.com/101194226/208291381-ddfcdc68-d37a-40e2-b027-b928fdf7f6d6.png)
