### ISSUE TITLE
Fix buttons on credentials tab (move when page is resized)

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/www-mastodon#125]

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

All of the buttons, fields, text, etc.. in the Credentials tab are now responsive and their size & location change according to the size of the window so they're visible at all sizes.

[Get Mastodon (38).webm](https://user-images.githubusercontent.com/101194226/208291922-051587f4-f472-48b7-a2df-8fcb483a6079.webm)
