### ISSUE TITLE
Disable instance helper buttons while deploying new instance

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/www-mastodon#127]
![image](https://user-images.githubusercontent.com/57001890/207564551-9c3559fe-50f4-4ae6-ba69-de252e524036.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/133

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

All instance buttons are now disabled while deploying a new instance.

[Get Mastodon (35).webm](https://user-images.githubusercontent.com/101194226/208291075-7843302e-7977-4d9f-9eae-ce972b17da6a.webm)
