### ISSUE TITLE
listing deployment shouldn't take the mnemonics again

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#14]
![image](https://user-images.githubusercontent.com/41957921/203860575-26cbc068-b6b4-4b21-9836-2261c3e33245.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

Deployment listing now doesn't require the mnemonics to be entered again.

[Get Mastodon (6).webm](https://user-images.githubusercontent.com/101194226/204545006-af461ee8-f84d-4834-b59a-53b44f06b66d.webm)
