### ISSUE TITLE
Update grid client dependency to use rmb relays

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#140]
grid client dependency should be updated when the client is ready https://github.com/threefoldtech/grid3_client_ts/issues/479

this should be only applied once the upgrade reaches mainnet

**Comment by xmonader** [comment]
Given this will wait for a mainnet release of 3.9, it needs to be tracked on 3.10

**Comment by khaledyoussef24** [comment]
verified and deployed successfully using relay
![image](https://user-images.githubusercontent.com/110984055/237009173-9e2e8ad6-34e5-460a-a392-877ac46eaa64.png)
