### ISSUE TITLE
Packages are not installed on the browser, and the console raises an error

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/www-mastodon#144]
Trying to build/run the project locally, the build and run passed without any problem, but once I opened the browser I got the mentioned error.

![image](https://user-images.githubusercontent.com/57001890/221859958-7926f259-760e-4019-b354-a7b08d95a561.png)

**Comment by xmonader** [comment]
please close as fixed @Mahmoud-Emad
