### ISSUE TITLE
Unable to list deployments 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#146]
### Description 

Currently I have 2 active mastodon deployments and i'm unable to list any of them. when i enter my mnemonics it just keeps loading and the following errors are displayed in the console.

```
POST https://graphql.grid.tf/graphql 400
```
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nameContracts')
    at en (MastodonList.ab8b2292.js:1:847)
    at async k (MastodonList.ab8b2292.js:22:3965)
```

[Untitled_ Mar 12, 2023 11_23 AM.webm](https://user-images.githubusercontent.com/101194226/224536011-702b5d76-fb11-45a4-9a4e-cf46925816de.webm)

**Comment by Mahmoud-Emad** [comment]
same as https://github.com/threefoldtech/www-mastodon/issues/158 so I'll close this one
