### ISSUE TITLE
Update mastodon's flist to use an official threefold flist

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#150]
### Description

Mastodon is currently not using an official Threefold flist.

![image](https://user-images.githubusercontent.com/101194226/224540857-b81303d6-5c0c-4386-a104-f1a738968c9f.png)

**Comment by Mahmoud-Emad** [comment]
@maxux 
can you please promote this https://hub.grid.tf/omda.3bot/threefolddev-getmastodon-latest.flist to be the official mastodon one?

**Comment by maxux** [comment]
`omda.3bot/threefolddev-getmastodon-latest.flist` -> `tf-official-apps/mastodon-latest.flist` :)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The flist was updated.

`https://hub.grid.tf/tf-official-apps/mastodon-latest.flist`

![image](https://github.com/threefoldtech/www-mastodon/assets/101194226/9ee77f9f-53b7-4942-8016-bb0934423c49)
