### ISSUE TITLE
Account creation is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#151]
### Description

Account creation fails with the following error.

```
Error: Extrinsic tfgridModule.createTwin expects 2 arguments, got 1.

```

![image](https://user-images.githubusercontent.com/101194226/231770843-22e75867-226e-454c-9111-73de08c2597c.png)

### Steps to Reproduce

- Navigate to https://getmastodon.threefold.io/
- Click on `Create Account`

**Comment by Mahmoud-Emad** [comment]
**Closing according to duplicating here https://github.com/threefoldtech/www-mastodon/issues/154**
