### ISSUE TITLE
All nodes are appearing as offline

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#152]
### Description

All nodes are returned as offline even though these nodes are working normally from the playground and the dashboard and deployments are working fine on them.

[Screencast from 13-04-23 15:32:40.webm](https://user-images.githubusercontent.com/101194226/231775594-e28e1fbd-0bba-4f7a-b674-3970e082901f.webm)

**Comment by Mahmoud-Emad** [comment]
it's was a network issue
