### ISSUE TITLE
balance is approximated showing higher balance

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#157]
![image](https://user-images.githubusercontent.com/110984055/236815750-8fe95d84-43f9-4a5e-8534-1a46c3b02bcc.png)
![image](https://user-images.githubusercontent.com/110984055/236815892-f5d931a0-82b6-436a-9f7b-4f0de55f64e5.png)

balance should be shown without approximation

**Comment by Mahmoud-Emad** [comment]
I am currently working on https://github.com/threefoldtech/threefold_connect/issues/534, so the work will be paused until I finish the mentioned issue.

**Comment by Mahmoud-Emad** [comment]
there is an approach I think about it, what do you think if we set it as it and when the user hovers on it we display the real balance?

**Comment by Mahmoud-Emad** [comment]
should be updated in https://github.com/threefoldtech/www-mastodon/pull/169/

**Comment by khaledyoussef24** [comment]
verified , it is more clear now and more accurate
![image](https://github.com/threefoldtech/www-mastodon/assets/110984055/70513384-d16d-4c1f-8f12-22671a314ab8)
![Screenshot from 2023-05-23 12-14-52](https://github.com/threefoldtech/www-mastodon/assets/110984055/92f7236a-f10c-4117-ab44-cc491563961e)
