### ISSUE TITLE
smtp server fields should be cleared after being disabled in advanced options

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#159]
if  the SMTP is enabled and any field is filled you can not deploy even if you disabled it again
![image](https://user-images.githubusercontent.com/110984055/237012199-aed0bd75-0719-4ab2-9596-df1f774b4a2f.png)
steps to produce:

1. go to mastodon
2. fill the deployment info
3. go to advanced and enable smtp server
4. fill the email tab and delete it ![image](https://user-images.githubusercontent.com/110984055/237012996-7d06da7d-f915-4ba2-97fc-98746179c63c.png)
5. disable the smtp server
6. click on deploy (the deploy button is enabled but it will not work)
![image](https://user-images.githubusercontent.com/110984055/237013107-9663ef7b-6328-4c99-9da8-c705e66353a4.png)

**Comment by Mahmoud-Emad** [comment]
I am currently working on https://github.com/threefoldtech/threefold_connect/issues/534, so the work will be paused until I finish the mentioned issue.

**Comment by Mahmoud-Emad** [comment]
should be fixed in https://github.com/threefoldtech/www-mastodon/pull/167

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

Now validation errors from the smtp fields are ignored in case it gets disabled before deployment.

[Get Mastodon.webm](https://github.com/threefoldtech/www-mastodon/assets/101194226/8cad9fdb-b360-4051-b0be-b4d0c4f2e0a5)
