### ISSUE TITLE
can not log in into mastodon using admin credentials

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#160]
can not log in into mastodon using admin credentials only can signup as a new user or connect using tf connect
![Screenshot from 2023-05-09 09-44-10](https://user-images.githubusercontent.com/110984055/237015826-d9a14ddc-b699-40f9-bf9a-f2625010d911.png)
![Screenshot from 2023-05-09 09-42-49](https://user-images.githubusercontent.com/110984055/237015835-d5f9ad64-7326-4580-ad72-568de7c466b8.png)

**Comment by khaledyoussef24** [comment]
it worked if the password is 8 characters or more
the deploying validation is only for 6 characters
while mastdon require passwords to be 8 or more

**Comment by khaledyoussef24** [comment]
I think we may increase the validation from the getmastodon side to be minimum of 8 characters or the mastodon image to 6 characters 
![Screenshot from 2023-05-23 11-27-58](https://github.com/threefoldtech/www-mastodon/assets/110984055/14b68fad-ced7-48dc-891d-bd5a17105f19)

**Comment by Mahmoud-Emad** [comment]
@khaledyoussef24

The password requirements have been updated to require a minimum of 8 characters. However, there might be a missing update in the production mode. I will double-check to confirm.

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The password validation now accepts a minimum of 8 characters.

![image](https://github.com/threefoldtech/www-mastodon/assets/101194226/a362936a-54c1-4a59-9c6a-4b1118d8ae21)


and also in the sign-up page it was updated to 8 characters.

![image](https://github.com/threefoldtech/www-mastodon/assets/101194226/11036b47-d515-49f4-86f6-a664a4e57a6e)
