### ISSUE TITLE
cursor after deploying 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#161]
the cursor ai in details after deployment should not be changed most of the details may be needed to copy or used so the ui of the cursor is confusing
![Screenshot from 2023-05-09 08-59-33](https://user-images.githubusercontent.com/110984055/237032129-ce2c7730-2cd3-423a-a8e3-d2767b0cb8c9.png)
![Screenshot from 2023-05-09 08-59-24](https://user-images.githubusercontent.com/110984055/237032134-f63d9938-76ec-4adc-b9cd-a80bfed1b053.png)

**Comment by khaledyoussef24** [comment]
the issue still exists 
![image](https://github.com/threefoldtech/www-mastodon/assets/110984055/585648cb-4bfd-4080-a840-60acb1e70ea6)

**Comment by Mahmoud-Emad** [comment]
The cursor has been updated to a copy cursor in the development mode. However, it seems that there might be a missing update in the production mode, as the cursor hasn't been updated there yet.

![image](https://github.com/threefoldtech/www-mastodon/assets/57001890/89c1d5aa-b7d2-410f-bfe4-a36951a5e253)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The cursor was updated.

[Get Mastodon (1).webm](https://github.com/threefoldtech/www-mastodon/assets/101194226/fd8ee60a-c2ff-451f-9a46-102d243b0fb1)

The transition of the cursor can be seen in the video but for some reason the video didn't show the actual look of the cursor.

But the cursor looks exactly like the screenshot in the comment above.


> ![image](https://user-images.githubusercontent.com/57001890/241491715-89c1d5aa-b7d2-410f-bfe4-a36951a5e253.png)
