### ISSUE TITLE
deployment vm is not reachable and giving bad gateway

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#166]
deployed a mastodon from getmasdoton and contracts created but it is not reachable and not working giving bad gateway

![Screenshot from 2023-05-17 10-27-30](https://github.com/threefoldtech/www-mastodon/assets/110984055/500854bc-6543-44be-bb1e-0d24e7528a75)
![Screenshot from 2023-05-17 10-22-47](https://github.com/threefoldtech/www-mastodon/assets/110984055/4beacbb7-1ad5-4092-867a-6515ca926400)

![image](https://github.com/threefoldtech/www-mastodon/assets/110984055/8feb4f6d-832e-40d2-9a55-6cb51f972f38)
![Screenshot from 2023-05-17 10-39-43](https://github.com/threefoldtech/www-mastodon/assets/110984055/7ad7d4a4-c811-4da2-a919-c54dfb55a6e5)

**Comment by khaledyoussef24** [comment]
deployed a full vm on the same node and it is working fine

**Comment by Mahmoud-Emad** [comment]
so should we close it? it supposed to be a network issue
