### ISSUE TITLE
The deployed's contract doesn't contain the metadata 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#17]
![image](https://user-images.githubusercontent.com/41957921/203862613-091f8cff-149a-40c7-846c-333f6b796b2e.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps to produce**

1. go to weblets
2. go to mastodon tab
3. deploy a mastodon
4. go to contracts tab
5. check for contract metadata

![Screenshot from 2022-11-29 15-20-58](https://user-images.githubusercontent.com/110984055/204540182-ba86c26d-114c-4c32-91ec-198ef8569089.png)

**Comment by mohamedamer453** [comment]
Verified from https://getmastodon.threefold.io/

The Deployed contracts now contain metadata

![image](https://user-images.githubusercontent.com/101194226/204543514-5f1d4245-5288-4504-8844-a1ea8a09ffcd.png)
