### ISSUE TITLE
The message to save your mnemonics should be more obvious 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#18]
- should be in warning color
- only appears if the user clicked on the create account button

![image](https://user-images.githubusercontent.com/41957921/203863985-ebd922d7-af94-4753-8d18-33fa9cf49dd4.png)

**Comment by mohamedamer453** [comment]
Verified.

The message now only appears when the mnemonics are generated through the `Create Account` button and the message is in warning color and is very clear for the user.

[Get Mastodon (5).webm](https://user-images.githubusercontent.com/101194226/204538301-16cec0b2-b596-46c4-8b68-049930b76108.webm)
