### ISSUE TITLE
I pasted in the mnemonics but no indication if it got loaded or not, i see only create account

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#19]
![image](https://user-images.githubusercontent.com/64129/203864444-3a872dbc-3c4f-415c-bb65-279a6c4d66bd.png)

**Comment by MohamedElmdary** [comment]
This issue related to #27 @xmonader

**Comment by mohamedamer453** [comment]
Verified from https://getmastodon.threefold.io/

Pasting the mnemonics now works without any issues and it'll load your twin data, ssh key (if it was stored before), and your previous deployments will appear in the deployment list.

[Get Mastodon (6).webm](https://user-images.githubusercontent.com/101194226/204546208-c9328d21-b8fa-45ec-8b05-177232ccbf83.webm)
