### ISSUE TITLE
please insert your mnemonics message is weird at this position

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#21]
![image](https://user-images.githubusercontent.com/64129/203864619-e5d7fe5d-103c-45ef-850e-19526f61cd54.png)

After pasting the mnemonics and creating create account it shows the cost of the deployment,
![image](https://user-images.githubusercontent.com/64129/203864777-dcb6d32b-8b08-4ffd-b5a6-0f9ea45de624.png)

It's safe not to show any message until the user pastes in their mnemonics

**Comment by mohamedamer453** [comment]
Verified.

The `Please Insert Your Mnemonics` message was removed and the field for the deployment cost now appears after the mnemonics are entered.

![image](https://user-images.githubusercontent.com/101194226/204534709-66b083e3-662e-45ca-9c45-c36c680dfd55.png)
