### ISSUE TITLE
Showing details first view shouldn't be the json one 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#23]
![image](https://user-images.githubusercontent.com/41957921/203866343-deb6fbe1-e6e2-4840-a474-ac456a5542e5.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The `Details` are now shown first.

![image](https://user-images.githubusercontent.com/101194226/204547167-f3834ac2-35c7-4b4c-85ac-824bc9fcafca.png)
