### ISSUE TITLE
deployment logs should only show the logs emitted to the logs event

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#24]

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

It now shows only logs emitted from events instead of showing the full logs for every action in the deployment.

[Get Mastodon (7).webm](https://user-images.githubusercontent.com/101194226/204548040-88258e2d-3964-4fd2-84c7-87f4823df8af.webm)
