### ISSUE TITLE
Threefold Connect app to download link

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#25]
the current link is for the play store only

### suggestion

- use 2 buttons like this image to download it from both stores

![image](https://user-images.githubusercontent.com/41957921/203867275-71b311e6-9018-43c6-a4c4-312703d81a8e.png)

**Comment by xmonader** [comment]
updated partially to d7ca0e72ac73e29fbe1a8638cba89a823fea4559

**Comment by MohamedElmdary** [comment]
## Fixed
![image](https://user-images.githubusercontent.com/31689104/204132063-2fadfdfc-b848-43f6-b8a0-83e394f0b8c2.png)

**Comment by mohamedamer453** [comment]
Verified.

The `Threefold connect` link redirects to the [docs](https://library.threefold.me/info/threefold#/tokens/threefold__threefold_connect) of Threefold connect.

![image](https://user-images.githubusercontent.com/101194226/204535295-39d8388f-d9e2-4be0-823e-b2e09057e9db.png)

and as seen in the screenshot, two new icons were added for both the google play store and the apple app store.

`Google Play` redirects to: https://play.google.com/store/apps/details?id=org.jimber.threebotlogin&hl=en&gl=US
`App Store` redirects to: https://apps.apple.com/us/app/threefold-connect/id1459845885
