### ISSUE TITLE
restore solutionProviderId 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#26]
it's approved now https://github.com/threefoldtech/www-mastodon/commit/d0bfbfabbb39070dc5f37607e863965461bc5b58

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The solutionProviderId field was removed from the deployment options

![image](https://user-images.githubusercontent.com/101194226/204548792-1b2975f1-bb66-4232-aba1-810f0a27d22e.png)

![image](https://user-images.githubusercontent.com/101194226/204548610-22f17219-7314-4a5b-ab83-0010e88377bc.png)
