### ISSUE TITLE
Binding not working on production mode

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/www-mastodon#27]

**Comment by MohamedElmdary** [comment]
## Fixed
https://github.com/threefoldtech/www-mastodon/tree/82b9c5844e08f3049347e1be5874b4342c1810d8

**Comment by mohamedamer453** [comment]
The issue was fixed and verified in https://github.com/threefoldtech/www-mastodon/issues/19#issuecomment-1330680833
