### ISSUE TITLE
Show code-server and webmin in the deployment details

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#29]
- code-server is running on port 8001
- webmin is running on port 8002

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

code-server and webmin urls are now shown in the deployment details with links to access both.

![image](https://user-images.githubusercontent.com/101194226/204566757-2a2ea44d-a90a-4cc1-be3d-9caf19943b6d.png)

[Untitled_ Nov 29, 2022 5_17 PM.webm](https://user-images.githubusercontent.com/101194226/204571747-3c216b64-05f1-4d97-8f19-722cd560ad34.webm)

and both are working and can be accessed with the admin email and password

![image](https://user-images.githubusercontent.com/101194226/204571886-52cb0783-2f9e-47c2-9854-2ddb7b399378.png)

![image](https://user-images.githubusercontent.com/101194226/204571986-f39e5aba-ce19-4fc5-b65b-81d653903998.png)
