### ISSUE TITLE
Superuser email and password are not working in the basic deployment 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#30]
### Description

After deploying an instance through the `Basic` Tab i was not able to access it through the provided `SUPERUSER_EMAIL` & `SUPERUSER_PASSWORD`.

[Untitled_ Nov 28, 2022 12_07 PM.webm](https://user-images.githubusercontent.com/101194226/204251273-c7e64ea3-806a-4e0f-8135-e50ac80faa02.webm)

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
If you still have your instance can you log into it and do `zinit log`?

**Comment by mohamedamer453** [comment]
> @mohamedamer453 If you still have your instance can you log into it and do `zinit log`?

Unfortunately the instance seen in the issue was deployed with a generated ssh key so i was not able to access it, so i created another one with my ssh key and i got the same error when i tried to login with the superuser email and password, and here are the full logs from this instance.
https://gist.github.com/mohamedamer453/c53d3c2b42e96cd93acc935018b5cf64

**Comment by mohamedamer453** [comment]
I forgot to mention that logging in to both instances using ThreeFold Connect was working without any issues, the only thing that did not work was using the admin email and password.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
@MohamedElmdary 
ah, as I understand `mastodon` does not accept a username as `admin` as you see in your gist file line `163`
https://gist.github.com/mohamedamer453/c53d3c2b42e96cd93acc935018b5cf64#file-mastodon_logs-txt-L163
they return `Validation failed: Username is reserved (ActiveRecord::RecordInvalid)`
also, it'll happen if you sent your mail as `admin@xx.x`, so we should add a validator on it as we did in the `mastodon-weblet`.

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

A validation was added to both the admin email and admin user name to prevent the user from using it as `admin@xx.x` for the email and `admin` for the username 

![image](https://user-images.githubusercontent.com/101194226/204554500-dc62b580-f17e-4e49-9da0-0df2309218f8.png)

![image](https://user-images.githubusercontent.com/101194226/204554947-539adae4-ae8c-4328-bebb-1b878fcc4cae.png)

and the deploy button was disabled in both cases.

and as seen below i'm now able to login with the admin credentials without any issues.

[Untitled_ Nov 29, 2022 4_27 PM.webm](https://user-images.githubusercontent.com/101194226/204555832-fb16ce4b-9116-49f5-a313-c54c1cab1d82.webm)
