### ISSUE TITLE
Basic Deployment: Admin Password

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#31]
### Description

 The basic deployment doesn't have an admin password field. and it is auto generated and currently only available in the JSON Deployment details. 

![image](https://user-images.githubusercontent.com/101194226/204252133-ce97bdd3-182d-4ebf-9be5-09f435ed783b.png)

so the admin password should either be a field in the basic deployment or the superuser email and password should be added in the deployment details tab.

![image](https://user-images.githubusercontent.com/101194226/204252471-08e3c884-7229-45e2-a14e-11c5c8321a07.png)

**Comment by MohamedElmdary** [comment]
it's already exists but there was an issue in production that blocking some fields from showing up
![image](https://user-images.githubusercontent.com/31689104/204253552-7a3d24cd-1298-4644-9f91-e60a52c13580.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

All admin credentials are now displayed in the deployment details.

![image](https://user-images.githubusercontent.com/101194226/206418844-1d979688-905f-4160-abc2-cd8611a5c9b5.png)
