### ISSUE TITLE
Basic Deployment: Region Filtering is not working correctly 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#34]
### Description

The region filtering in the basic configuration is not working correctly. it's only available for deployment when the region is either `Asia` or `Europe` but it doesn't work with `Africa`, `Oceania`, or `Americas` even though there are multiple nodes available in each of these regions according tho the explorer.

[Get Mastodon.webm](https://user-images.githubusercontent.com/101194226/204259318-17e2f03e-33f9-4e06-b9ad-1cbdd8a999c0.webm)

and according to the statistic page and map distribution there are nodes in each of these regions.

![image](https://user-images.githubusercontent.com/101194226/204259576-a75905c6-45e2-40cc-82f7-67be1b76bd8f.png)

North America: 1000+ Nodes
South America: 3 Nodes
Africa: 10 Nodes
Oceania: 70 Nodes

**Comment by MohamedElmdary** [comment]
After some investigation discovered that nodes Filter only returns first 50 nodes that fulfil the requirements.
If we pick farm `brautech-3bot(2317)` and pick region `Africa`
We'll find nodes (*3882*, *3954*) which proves the issue
@AhmedHanafy725 @mohamedamer453

**Comment by mohamedamer453** [comment]
The issue is still valid. All the mentioned regions still report that there were no nodes found.

![image](https://user-images.githubusercontent.com/101194226/208296583-ac2a2a32-7de0-41fc-9bd6-4c9a04647ebc.png)

![image](https://user-images.githubusercontent.com/101194226/208296595-cf3c027c-5841-494d-abdb-a10fae573471.png)

![image](https://user-images.githubusercontent.com/101194226/208296618-e2480a18-f3b9-4cc3-be6f-131f8cf456d4.png)



> After some investigation discovered that nodes Filter only returns first 50 nodes that fulfil the requirements.

and indeed as mentioned above this was the issue because when i changed the disk to `1000` instead of `100` it returned the first 50 nodes that had `1000` gb of sru, then i selected `Americas` in the region and it returned these nodes.

![image](https://user-images.githubusercontent.com/101194226/208297032-d134dce5-ed6e-46b7-8702-75e8afdc27fa.png)

**Comment by khaledyoussef24** [comment]
steps to verify :
1-go to [mastodon](https://getmastodon.threefold.io/)
2-insert your credentials 
try to choose a region if it is not available 
![Screenshot from 2023-01-23 15-19-47](https://user-images.githubusercontent.com/110984055/214055058-4612b13c-ec57-42bc-87b3-fb9bffb664d9.png)
3-go to advanced try to choose the farm and the nodes and make sure that they are down or filled
![Screenshot from 2023-01-23 15-38-49](https://user-images.githubusercontent.com/110984055/214054829-0a11fcf9-de0d-405c-8765-a0402b3f4d0f.png)
![Screenshot from 2023-01-23 15-38-01](https://user-images.githubusercontent.com/110984055/214054830-6be8ebc9-487c-4494-b43a-e0d4d2e5b53e.png)
