### ISSUE TITLE
Display the balance of the user

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#36]
### Description

The balance of the user is not displayed anywhere in the website, and therefore the user has no idea when the account runs out of tokens.

or even when the balance is not enough to deploy an instance.

![image](https://user-images.githubusercontent.com/101194226/204283006-196d5ecb-85b8-49e8-ab68-6312b6937fac.png)

**Comment by Mahmoud-Emad** [comment]
should be fixed in https://github.com/threefoldtech/www-mastodon/pull/57

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The balance of the user was added.

![image](https://user-images.githubusercontent.com/101194226/205484311-e604b61a-916e-42d8-a7d5-2bf141ffbe4e.png)

however there is an issue with it covering part of the description as discussed in #61
