### ISSUE TITLE
SSH Key is not updated when the mnemonics are changed

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#37]
### Description

When the user enters different mnemonics from the loaded one it doesn't update the ssh key until the page is refreshed.

As seen in the video below, firstly i had a loaded mnemonics with its ssh key, then i changed the mnemonics but the ssh key was not loaded until i refreshed the page.

[Get Mastodon (1).webm](https://user-images.githubusercontent.com/101194226/204305156-e9e5d78d-4efe-4972-b6f4-88bf933a1854.webm)

**Comment by mohamedamer453** [comment]
The mentioned issue doesn't exist anymore but a new issue appeared.

As seen below now when i enter different mnemonics with a different stored key, it did not load the key of the other mnemonics and it stores the key of the previous mnemonics to the added mnemonics.

It might be the same behavior seen in https://github.com/threefoldtech/www-mastodon/issues/22#issuecomment-1330647298 where the ssh key is stored every time the user loads the mnemonics.

[Get Mastodon (9).webm](https://user-images.githubusercontent.com/101194226/204558353-68ac804b-98a4-4c5d-9ef6-50ee0d167d5c.webm)

**Comment by mohamedamer453** [comment]
Also if the ssh key is empty and you try to load another mnemonics it will not load the key of the added mnemonics until you reload the page.

[Get Mastodon (12).webm](https://user-images.githubusercontent.com/101194226/204800143-5f8f58df-26f6-4b08-85e4-44d759641055.webm)

**Comment by mohamedamer453** [comment]
This issue is still valid and a good fix for it would be clearing the ssh field when the mnemonics are incorrect/removed/replaced to prevent this from happening

> As seen below now when i enter different mnemonics with a different stored key, it did not load the key of the other mnemonics and it stores the key of the previous mnemonics to the added mnemonics.


[Get Mastodon (41).webm](https://user-images.githubusercontent.com/101194226/208301510-6fb74559-3202-4426-b537-625d1ee637b4.webm)

**Comment by khaledyoussef24** [comment]
verified:

1. steps to produce go to [mastodon](https://getmastodon.threefold.io/)
2. insert your credentials (if the first time insert your ssh key also and reload)
3. wait for the ssh key to load
4. try to remove part of it
5. re insert your Mnemonics


[Screencast from 01-23-2023 04:36:21 PM.webm](https://user-images.githubusercontent.com/110984055/214066972-4c7911b7-5db3-4ef4-91cd-89cd942b8d77.webm)
