### ISSUE TITLE
The `Mnemonics` field does not accept more than one character at a time

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#38]
### Description

The `Mnemonics` field does not accept more than one character at a time. and to enter a full word you have to click inside the field after every character.

[Get Mastodon (2).webm](https://user-images.githubusercontent.com/101194226/204307819-8dfb2bd9-bd35-449e-ba6f-64c4cabf557c.webm)

**Comment by zaelgohary** [comment]
This is a known issue as all users paste their mnemonics directly in the field.

**Comment by khaledyoussef24** [comment]
verified locally waiting to be released on main net
