### ISSUE TITLE
Round the deployment cost value

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#39]
### Description

Sometime when the resources are changed to certain values the deployment cost will be displayed with up to 10 decimals as seen below.

![image](https://user-images.githubusercontent.com/101194226/204321297-310c966f-8ec7-42db-bd37-20bf31446855.png)

it would look better if the values were always rounded to 2 or 3 decimals

**Comment by Mahmoud-Emad** [comment]
Should be fixed in #55

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The deployment cost is now rounded to 2 decimals.

![image](https://user-images.githubusercontent.com/101194226/205484452-55e040c3-6bed-401a-b72f-3eb137b01e08.png)
