### ISSUE TITLE
Add Billing Rate

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/www-mastodon#40]

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The billing rate was added and as seen in the screenshots it matches the rate from the Contracts list.

![image](https://user-images.githubusercontent.com/101194226/204562267-00ae5d89-3c4d-4fe6-af24-92b639cc93d5.png)

![image](https://user-images.githubusercontent.com/101194226/204562417-f88d00d5-c19d-46e6-9198-c3938fc9ce0d.png)

However i noticed an issue where the billing rate doesn't add the values for the name and gateway contracts so i created a separate issue for it #42
