### ISSUE TITLE
Add warning message for funding the account before generating the ssh key

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#48]
### Description 

Add a warning message to let the user know that the generated ssh key will not be stored unless there's balance in the account, because currently after generating the key without having enough balance this message will be displayed and it's not clear for the user.

![image](https://user-images.githubusercontent.com/101194226/204795920-8b5e9bb5-1973-43e5-9871-919a4c38ef01.png)
 
It would look better if it was in the same color and format as the message for storing the mnemonics. 
and for the `Balance is not enough to apply an extrinsic` message it should be `Balance is not enough to store your ssh key` and it should be in warning color not in green.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453  
should be fixed in https://github.com/threefoldtech/www-mastodon/issues/44
now once the user enters his mnemonics we chicking his balance, in case he hasn't enough balance we disable the deploy button and return a clear message to him outside the mnemonics input as an error message.

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

After generating new mnemonics, an error message will be displayed next to the mnemonics that your balance is not enough. and the deploy button will be disabled until the account is funded.

![image](https://user-images.githubusercontent.com/101194226/205484620-c0a28451-cc1e-4588-a0ee-a8e8e899632f.png)
