### ISSUE TITLE
`Your mastodon instance is up and running` doesn't disappear after you change the page 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#49]
### Description 

The `Your mastodon instance is up and running.` message didn't disappear after i returned to the deployment config tab. and it's still there even after i deleted the instance.

![image](https://user-images.githubusercontent.com/101194226/204836660-d939225c-4e60-4054-98ad-e9219f8bfa8c.png)

**Comment by Mahmoud-Emad** [comment]
should be fixed in https://github.com/threefoldtech/www-mastodon/pull/54

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The message now disappears after returning from the deployment.

[Get Mastodon (17).webm](https://user-images.githubusercontent.com/101194226/205486846-4c484721-1703-4e6a-a88b-c5231756120a.webm)
