### ISSUE TITLE
Testing scenarios

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#5]
- The user is able to generate mnemonics without any previous requirements.

- The user is able to generate ssh key.

- The private ssh key should be available for the user to download once it's generated.

- There should be a warning/reminder for the user to save the mnemonics after it's generated.

- QR code is visible and is working without any issues.

- The price of the default package is displayed and will be updated when the user changes the resources of the deployment.

- The discounted price is also visible for the user.

- After generating ssh key and mnemonics, the user is able to configure the deployment either with basic or advanced config.
	
- The user should be allowed to deploy with basic config.

- The user should be allowed to deploy with advanced config.

- The user should be allowed to deploy with threefold connect option.

- The user should be able to list previous deployments using the generated mnemonics.

- Same deployment scenarios but with already existing mnemonics/ssh key.

- Verify that the certified option deploys on certified nodes.

- A brief docs about mastadon should be included at the top of the page and a link for the `Quick Start docs` and it should redirect the user to the correct path in the threefold manual.

- A link to download `Threefold Connect` should be available.

- Input validation should be available fields with the appropriate parameters.

- The user should be able to access the instance with the provided admin email and password.

- Verify that the selected resources are reflected correctly in the deployment.

-  After a successful deployment verify that the user is able to check the full deployment details and the JSON output of the deployment.

- Verify that the user is able to delete any deployed instances without any issues.

- The deployment price should be updated if the user changes any resources.

- A clear error message should be visible for the user if the balance of the twin is not enough.

- The user should not be able to deploy an instance with insufficient balance, and clear message should appear for the user mentioning that the balance is not enough.

- After selecting a Region and deploying an instance on it, verify that the selected node belongs to the selected region.

- In the advanced options when a user selects a certain farm/farm id verify that the deployed instance was deployed on a node that belongs to this farm.

- There should be a message warning the user that the ssh key will not be stored in the case that the account was not funded.

- The basic and advance config tabs should not appear unless a valid public ssh key is entered.

- In the basic config, the mastodon instance name should be the used subdomain.

- In the advanced config , verify that the user is able to select any of the available gateways and that domain is reflected correctly after the deployment.

- In the advanced config, verify that the user is able to deploy an instance with public IPv4 and can access the instance with the same IP.

-  In the advanced config, after deploying on a specific node verify that the instance was deployed on the mentioned node.

-  In the advanced config, verify that the SMTP Server settings are optional.

-  In the advanced config, verify that the user can deploy an instance with configured SMTP settings.

**Comment by sasha-astiadi** [comment]
can we have a call on this please, id like to get an explanation on the user journey start to finish.
https://www.figma.com/file/KhU2r4URXL8MBfF2TUs3NS/Mastodon?node-id=0%3A1&t=1fXUCSQ3TAisINYw-0

id like to give the command instructions because i might understand it from user perspective, instead of developers perspective.

**Comment by mohamedamer453** [comment]
The scenarios mentioned above plus more scenarios were added in the Mastodon test suite on test lodge https://app.testlodge.com/a/26076/projects/40893/suites/217977 and it's still being updated with every new feature added/fixed.
