### ISSUE TITLE
Text and experience updates

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/www-mastodon#50]
**HOME**

Deploy a Mastodon Instance
Mastodon is free and open-source software for running self-hosted social networking services. It has microblogging features similar to the Twitter service, which are offered by a large number of independently run nodes, known as instances, each with its own code of conduct, terms of service, privacy options, and moderation policies.

_to_

Deploy a Mastodon Instance on top of ThreeFold
Mastodon is free and open-source software for running self-hosted social networking services. It has microblogging features similar to Twitter, which are offered by a large number of independently run nodes, known as instances or servers, each with its own code of conduct, terms of service, privacy options, and moderation policies.

---

Mnemonics are your private key, they are used represent you on Threefold Grid. You can paste existing mnemonics or click on the generate button to create a new account.

_to_

Mnemonics are your private key. They are used to represent you on the ThreeFold Grid. You can paste existing mnemonics or click the "Create Account" button to create an account and generate mnemonics.

---

_After hitting "Create Account"_

The deployment will cost 3.6144 USD/Month for 50K Balance after applying discount

_to_

The deployment will cost 3.6144 USD/Month with a 50k balance of TFT, after applying discount.

_Also ..._

Please make sure to store your mnemonics somewhere safe to be able to access your deployments

_to_

Please make sure to store your mnemonics somewhere safe to be able to access your deployments later on. There is no way for neither you nor ThreeFold nor anybody else to recover lost mnemonics.

---

Scan QRcode using Threefold connect to fund your account.

_to_

Scan the QR code using ThreeFold Connect to fund your account.

---

SSH keys are used to authenticate you to the mastodon instance for management purposes.If you don't have one, or not familiar with it, we can generate one for you.

_to_

SSH Keys are used to authenticate you to the Mastodon instance for management purposes. If you don't have an SSH Key or are not familiar, we can generate one for you.

---

_After hitting "Generate SSH Key"_

Balance is not enough to apply an extrinsic

_to_

(This is not good but I don't know what is trying to be said, can help if I get some clarity.)

**BASIC**

Instance name is used as for managing the deployed instance and to create a subdomain

_to_

Instance name is used for managing the deployed instance and to create a subdomain.

---

Under "Region," why do we have Antarctic Ocean and Antarctic?

---

Enable Threefold Connect >> Enable ThreeFold Connect

---

**GENERAL**

We need to make it more user-friendly for people to know how to work with the weblet. I think we need a link to the manual so that people where people can understand how to work with the Basic and Advanced tabs. Can we also link to the forum / place live chat on the website? Maybe we should add a header:

- ThreeFold + Mastodon logos
- Link to manual
- Link to forum
- Link to blog on threefold.io about Mastodon + ThreeFold
- Link back to threefold.io

**Comment by xmonader** [comment]
texts updated on https://github.com/threefoldtech/www-mastodon/pull/51
and regions update on https://github.com/threefoldtech/www-mastodon/pull/52

**Comment by xmonader** [comment]
https://github.com/threefoldtech/www-mastodon/issues/50 for the parts mentioned in the general notes, it's just a `weblet`, to be embedded in websites, not a website by itselff
