### ISSUE TITLE
add spacing before the logs box

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#58]
![image](https://user-images.githubusercontent.com/64129/205106901-6b05b3af-ccfa-45fb-9da2-dc011ff13864.png)

**Comment by Mahmoud-Emad** [comment]
Should be improved in https://github.com/threefoldtech/www-mastodon/pull/68

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

A space was added before the logs box.

### Full screen

![image](https://user-images.githubusercontent.com/101194226/205928254-309b56ff-8c32-45f5-93db-b3ec8bdc2c9b.png)

### Minimized 

![image](https://user-images.githubusercontent.com/101194226/205927988-5b150140-03ae-46d1-bc98-a0cc55108f03.png)
