### ISSUE TITLE
Delete Deployment: Confirmation & Messages

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#60]
### Description

A confirmation message should be added when the user clicks on the delete button instead of instantly deleting the deployment. and a success message should be added when a deployment is successfully deleted and if there is an error message (ex: not enough balance) there should be a clear message displayed with the mentioned error.

**Comment by Mahmoud-Emad** [comment]
should be implemented in https://github.com/threefoldtech/www-mastodon/pull/67
simple view 


![image](https://user-images.githubusercontent.com/57001890/205494950-c11b3f15-1831-4bcb-be38-3aaf943bc227.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

Extra confirmation was added before deleting an instance it it'll only allow the user to delete the instance if the instance name was entered correctly.

![image](https://user-images.githubusercontent.com/101194226/205950112-1edb8bc0-4a3d-49cd-8abe-be1df38b0c72.png)

and it also works if you want to delete multiple deployments. you'll have to enter the names of the instances separated by a comma.

![image](https://user-images.githubusercontent.com/101194226/205952374-3a9d0085-f604-4c93-9acb-de4cd31e8fae.png)

![image](https://user-images.githubusercontent.com/101194226/205952500-3df574c3-1dac-4640-9794-36d88e450b1d.png)
