### ISSUE TITLE
UI: User balance blocks part of the description at certain resolutions/window sizes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#61]
### Description

The user balance box is blocking a part of the description. at certain resolutions/window sizes. it appeared fine on a 1920x1080 monitor but only when its full screen. however on a 2560x1440 monitor the text was blocked both when it was on full screen and when it was minimized as seen in the screenshots below.

- Full Screen

   ![image](https://user-images.githubusercontent.com/101194226/205483098-865cdeb9-02c5-4028-9d08-7e1a752445be.png)

- Minimized

   ![image](https://user-images.githubusercontent.com/101194226/205483110-45124c95-e5d0-4a1e-be34-f78235e87916.png)

And it also clips through the successful deployment message.

- Full Screen

   ![image](https://user-images.githubusercontent.com/101194226/205483068-7c910c9a-58e2-4c9b-833e-b34cb7c2a0ff.png)

- Minimized

   ![image](https://user-images.githubusercontent.com/101194226/205483082-1dd936f5-b8c9-4b47-a460-b0adb9692b68.png)

**Comment by Mahmoud-Emad** [comment]
Should be improved in https://github.com/threefoldtech/www-mastodon/pull/68

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The size of the balance box now changes dynamically according to the window size/screen resolution. and a space was added before and after it to prevent it from covering the description or the deployment info box.

### Full screen

![image](https://user-images.githubusercontent.com/101194226/205929286-3585e3db-244b-4303-af5c-0cdca828fb82.png)


### Minimized

![image](https://user-images.githubusercontent.com/101194226/205929325-b7647895-3fe5-4ee6-b9d7-79a0c07c591c.png)
