### ISSUE TITLE
Balance Doesn't appear for generated accounts

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#62]
### Description 

The user balance did not appear for newly generated twin even after funding the twin and being able to access the basic and advanced deployment tabs i was not able to see the balance.

In the video below, i had the mnemonics of one of my previously created accounts loaded and the balance was visible for this account without any issues, then i entered the mnemonics of the account that i generated from the `Create Account` button and the balance did not appear for this one even though i had access to the basic and advanced tabs since this account already had tfts in it.

[Get Mastodon (15).webm](https://user-images.githubusercontent.com/101194226/205485539-278653e9-9112-4727-b424-ff932289176b.webm)

### Steps to Reproduce

- Navigate to https://getmastodon.threefold.io/
- Click on `Create Account`
- Wait for the account to be created then fund your account.
- Refresh the page.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/68

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The balance now appears for generated accounts once the account is funded.

[Get Mastodon (22).webm](https://user-images.githubusercontent.com/101194226/205948184-a5fa153e-1624-42af-a261-173c809b58cb.webm)
