### ISSUE TITLE
`Mnemonics` field validation is activated before the user enters anything

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#63]
### Description 

The validation message for the `Mnemonics` field is activated even before anything is entered in this field.

![image](https://user-images.githubusercontent.com/101194226/205487073-ded2dd71-e109-44f7-8672-2437896ed506.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/72

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The validation of the `Mnemonics` field was fixed and now it doesn't get activated before the user interacts with it.

[Get Mastodon (23).webm](https://user-images.githubusercontent.com/101194226/206169390-258287e1-33a2-40ca-9439-384a0f4afcf0.webm)
