### ISSUE TITLE
Disable generating/loading ssh keys before funding the account

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#64]
### Description 

The `Generate SSH Key` button & the ssh field should be disabled until there is enough balance in the account, because if the user generates a key pair or adds a public ssh key before funding the account it will not be stored and linked to the mnemonics and it'll be more confusing for the user. so disabling the button & field until the account is funded will be easier to use/understand.

In the video below, firstly i generated new mnemonics using the `Create Account` button then i generated a ssh key pair before funding the account, lastly i funded the account then i reloaded the page and the ssh key i generated was not stored since it was generated before funding the account.

[Get Mastodon (18).webm](https://user-images.githubusercontent.com/101194226/205487551-82b4af3f-ce52-4b84-9895-c0eb90d23080.webm)

### Steps to reproduce

- Navigate to https://getmastodon.threefold.io/
- Click on `Create Account`
- Click on `Generate SSH Key`
- Fund you account
- Reload the page

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/71

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The `Public SSH Key` field and the `Generate SSH Key` button are now disabled when the balance is not enough.  

![image](https://user-images.githubusercontent.com/101194226/205943405-ef998062-ba76-4f10-863f-c4776a472c7e.png)

And they are enabled once there's enough balance in the account.

![image](https://user-images.githubusercontent.com/101194226/205946362-0b247226-09e7-47a8-98d6-bc10c8ce3ecd.png)
