### ISSUE TITLE
broken bridge link mainnet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#7]
[git@github.com:threefoldtech/www-mastodon.git](https://github.com/threefoldtech/www-mastodon/blob/8ef276c64429feec11b89af848e42cabc8fed229/src/tabs/Credentials.svelte#L128)

**Comment by AhmedHanafy725** [comment]
the bridge address should be based on the network

devnet: `GDHJP6TF3UXYXTNEZ2P36J5FH7W4BJJQ4AYYAXC66I2Q2AH5B6O6BCFG`
testnet: `GA2CWNBUHX7NZ3B5GR4I23FMU7VY5RPA77IUJTIXTTTGKYSKDSV6LUA4`
mainnet: `GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC`

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io

The bridge address scanned from the QR code is correct and it's the same one for mainnet as mentioned above.

> mainnet: `GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC`

![image](https://user-images.githubusercontent.com/101194226/205481204-4b4412e3-badf-42d7-b763-cd185aee71db.png)

And i was able to transfer tfts to my twin by scanning the qr code without any issues.
