### ISSUE TITLE
Can't deploy on a certified node

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/www-mastodon#73]
Whenever I chose to have a certified node, with all inputs are valid.
It doesn't show me any available node.

![image](https://user-images.githubusercontent.com/109473873/205670796-6d1aac83-efef-4ab9-b3c8-2ffd7cd5e5b4.png)
![image](https://user-images.githubusercontent.com/109473873/205670074-b26a54e7-3681-4ec3-9414-4973e6671d6e.png)

List is empty.
![image](https://user-images.githubusercontent.com/109473873/205670902-7a418808-24f5-4a76-b44d-a4c80a31ee6d.png)

**Comment by mohamedamer453** [comment]
A clear error message was added when there are no nodes in the selected region https://github.com/threefoldtech/www-mastodon/issues/90#issuecomment-1342963533. however this issue is related to the `Certified` option not working and not returning any nodes, even when the region is set to `All`
