### ISSUE TITLE
Instance Failed to start and stuck in the `Waiting for your mastodon instance` as a result 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#74]
### Description

A mastodon instance failed to start and as a result it was stuck in the `Waiting for your mastodon instance to be up and running` for 10+ minutes until i refreshed the page. and the instance is still giving bad gateway till now.

### Logs

Full logs of the machine: https://gist.github.com/mohamedamer453/e2fbc543b4d96e1393f7db13c0c4eda4

Deployment Details:
```json
{
    "version": 0,
    "contractId": 11383,
    "nodeId": 1,
    "name": "testmastodon",
    "created": 1670253165,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/mastodon-latest.flist",
    "publicIP": null,
    "planetary": "300:1b0f:ec2d:be82:fd8f:b2ed:3e7f:1472",
    "interfaces": [
        {
            "network": "NWlkjcc9yrgn5p6",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 1,
        "memory": 1024
    },
    "mounts": [
        {
            "name": "diskh6p71jhnua8",
            "mountPoint": "/var/lib/docker",
            "size": 107374182400,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "LOCAL_DOMAIN": "md7989testmastodon.gent01.grid.tf",
        "SUPERUSER_USERNAME": "admin_mastodon",
        "SUPERUSER_EMAIL": "test@email.com",
        "SUPERUSER_PASSWORD": "admin123456",
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "IS_TF_CONNECT": "true"
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "{\"type\":\"vm\",\"name\":\"testmastodon\",\"projectName\":\"Mastodon\"}",
    "description": "",
    "corex": false
}
```

**Comment by mohamedamer453** [comment]
Update: the instance started now but it's almost 25 mins after the instance was created.

another thing to mention is that the instance is very slow in performing any task and not very responsive.

**Comment by mohamedamer453** [comment]
after checking the webmin dashboard for this instance i think that the problem is due to low resources 

![image](https://user-images.githubusercontent.com/101194226/205693856-4477767c-7227-4b64-8345-a7e9c39fbde0.png)


since this instance was deployed with 1 vCore and 1gb ram

```
"capacity": {
        "cpu": 1,
        "memory": 1024
    }
```

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/87

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/87

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

A validation was added to raise the minimum allowed resources to `2GB` of memory And `20GB` of disk size

![image](https://user-images.githubusercontent.com/101194226/206203654-0fab431c-9561-4b38-a6da-5a205c0153fb.png)

and i've deployed an instance with the min resources for everything 

```
  "capacity": {
            "cpu": 1,
            "memory": 2048
        },
        "mounts": [
            {
                "name": "diskyau87dstjta",
                "mountPoint": "/var/lib/docker",
                "size": 21474836480,
                "state": "ok",
                "message": ""
            }
```

and didn't encounter any issues with it or notice any slowness in the instance itself unlike what was happening in the instance with the old minimum requirements.

and here are the resources usage from webmin showing acceptable usage percentage and nothing is maxed out.

![image](https://user-images.githubusercontent.com/101194226/206207067-4778cdfc-c10d-40b1-9efe-9679b41ad469.png)
