### ISSUE TITLE
Offline nodes are listed `Select Node ID`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/www-mastodon#75]
After Adding all the data correctly and select a node randomly from the list, deployment fail cause node is offline.

![image](https://user-images.githubusercontent.com/109473873/205679041-ce42c7fc-b562-42d4-8337-8427f915eb4f.png)
![image](https://user-images.githubusercontent.com/109473873/205680277-b3ec7428-eb31-4709-95ae-3600eea13f76.png)

**Comment by A-Harby** [comment]
Also just checked node ID (321), and its online.
![image](https://user-images.githubusercontent.com/109473873/205692145-0ae8be5d-16c4-4fa6-bbf2-5f5508a44fc6.png)

And I was able to deploy VM on it and successfully ssh.
![image](https://user-images.githubusercontent.com/109473873/205695764-78f31207-d52d-4ae0-aa72-bd42bbdccc82.png)
![image](https://user-images.githubusercontent.com/109473873/205695630-a5e996aa-5b52-4032-830b-dd204cf876ac.png)

Occurred again (Public IPV4 switch is on). 
![image](https://user-images.githubusercontent.com/109473873/205694007-daf88b31-38f4-4801-ac35-8ab91e8e8de8.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/.

Now the user will not be able to deploy on an offline node.

[Get Mastodon (33).webm](https://user-images.githubusercontent.com/101194226/206515444-e1bfa6e6-501f-4127-bfb0-ec20e040a80d.webm)

However the issue with the mentioned nodes is still present so i created a separate issue for it #108 
and another issue for the time it takes to check the status of a node #109
