### ISSUE TITLE
webmin issues

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#78]
Kristof De Spiegeleer, [12/5/22 7:16 PM]
in webmin.acl need to set other security

Kristof De Spiegeleer, [12/5/22 7:16 PM]
root: acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dovecot exim exports fail2ban fdisk fetchmail filemin filter firewall firewall6 firewalld fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin logrotate logviewer lpadmin lvm mailboxes mailcap man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd qmailadmin quota raid samba sarg sendmail servers shell shorewall shorewall6 smart-status smf software spam squid sshd status stunnel syslog-ng syslog system-status tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd
admin_mastodon:access privileges acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dovecot exim exports fail2ban fdisk fetchmail filemin filter firewall firewall6 firewalld fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin logrotate logviewer lpadmin lvm mailboxes mailcap man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd qmailadmin quota raid samba sarg sendmail servers shell shorewall shorewall6 smart-status smf software spam squid sshd status stunnel syslog-ng syslog system-status tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd

Kristof De Spiegeleer, [12/5/22 7:19 PM]
The Webmin module Scheduled Cron Jobs is not installed on this system or is not supported by your OS. The Bandwidth Monitoring module cannot operate without it.

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tf-images/pull/118 , there is an error with the flist once it is fixed we can build a flist ant test it.

**Comment by mohamedamer453** [comment]
After deploying an instance with the updated image it can be seen that alot of new features/info/notifications/etc.. are now available for the user. 

![image](https://user-images.githubusercontent.com/101194226/206177634-f28c0450-db2b-453e-8da1-0627120c3637.png)




> Kristof De Spiegeleer, [12/5/22 7:16 PM] in webmin.acl need to set other security
> 
> Kristof De Spiegeleer, [12/5/22 7:16 PM] root: acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dovecot exim exports fail2ban fdisk fetchmail filemin filter firewall firewall6 firewalld fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin logrotate logviewer lpadmin lvm mailboxes mailcap man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd qmailadmin quota raid samba sarg sendmail servers shell shorewall shorewall6 smart-status smf software spam squid sshd status stunnel syslog-ng syslog system-status tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd admin_mastodon:access privileges acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dovecot exim exports fail2ban fdisk fetchmail filemin filter firewall firewall6 firewalld fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin logrotate logviewer lpadmin lvm mailboxes mailcap man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd qmailadmin quota raid samba sarg sendmail servers shell shorewall shorewall6 smart-status smf software spam squid sshd status stunnel syslog-ng syslog system-status tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd

however for this part i was not able to understand what these logs related to/originated from or what should be verified in it.


> Kristof De Spiegeleer, [12/5/22 7:19 PM] The Webmin module Scheduled Cron Jobs is not installed on this system or is not supported by your OS. The Bandwidth Monitoring module cannot operate without it.

and in this part, i encountered the same error when i opened `Networking` -> `Bandwidth Monitoring`

![image](https://user-images.githubusercontent.com/101194226/206178523-f41710c7-8692-4386-b000-4281ea120231.png)

**Comment by JohnG1985** [comment]
It looks like the Webmin module Scheduled Cron Jobs is not installed or is not supported by your operating system. The Bandwidth Monitoring module depends on this module to function properly, so you will need to install and enable the Scheduled Cron Jobs module in order to use the Bandwidth Monitoring module.

To install the Scheduled Cron Jobs module, you can follow these steps:

Open the Webmin interface in your web browser.
Click on the "Webmin" menu, then click on "Webmin Configuration".
Click on the "Webmin Modules" tab.
In the "Search for new modules" section, enter "Scheduled Cron Jobs" in the search box and click the "Search" button.
The Scheduled Cron Jobs module should appear in the search results. Click on the "Install" button next to the module to install it.
The module will be downloaded and installed. Once the installation is complete, you should see the Scheduled Cron Jobs module listed under the "Installed Webmin Modules" section.
Click on the "Refresh Modules" button to refresh the list of available modules.
You should now be able to access the Scheduled Cron Jobs module by clicking on the "System" menu and selecting "Scheduled Cron Jobs".
Once the Scheduled Cron Jobs module is installed and enabled, the Bandwidth Monitoring module should be able to function properly.

**Comment by Mahmoud-Emad** [comment]
@JohnG1985 
Unfortunately, this solution does not work for me, I just tried many times to install this module with different sources as seen in the Webmin configuration UI, then I got that all resources can't find the module, you can take a look at [this issue](https://github.com/threefoldtech/www-mastodon/issues/104) I mentioned why it is not working
