### ISSUE TITLE
UX: In deployment process, the Deploy button should remain active all the time (clickable), but if you click it and can't continue for some reason, a pop up message should appear telling you the reason

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#79]

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/86 , now the button is not disabled but if there is an error the `Tab will activate and then focus on the error field

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The `Deploy` button is now enabled all the time even when there's a validation issue or something missing with any of the fields. but once the user click on `Deploy` when there are errors in any of the fields, the mentioned filed will be focused on even if it's in another tab, with a clear error message explaining what is wrong with the field.

here's a simple flow if only a couple of fields are invalid

[Get Mastodon (27).webm](https://user-images.githubusercontent.com/101194226/206199796-1903bff2-8a14-4c1f-bba8-fe654ed8c4cf.webm)

and here's a video showing it work with every field

[Get Mastodon (28).webm](https://user-images.githubusercontent.com/101194226/206199989-204c6b80-0c47-4158-b218-71a615602290.webm)

The only issues i encountered was: 
- The region field not showing any errors when i selected a region with no node. and it was already reported before in #20 
- And the Certified option not showing error messages when there are no certified nodes in the selected region https://github.com/threefoldtech/www-mastodon/issues/90
