### ISSUE TITLE
details doens't show the url

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#8]
![image](https://user-images.githubusercontent.com/64129/203851219-4384e0b2-0893-4841-8fc4-14ec37c9a591.png)

**Comment by mohamedamer453** [comment]
Verified from https://getmastodon.threefold.io/.

The details now show the url of the instance with a button that redirects you to the instance.

![image](https://user-images.githubusercontent.com/101194226/204544143-2363510c-bdfd-4cc3-b5b2-304ac9d444ca.png)
