### ISSUE TITLE
On Deployment List: Don't need to show Flist

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#82]

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/85

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

The flist was removed from the deployment list.

![image](https://user-images.githubusercontent.com/101194226/206180448-ca7bebf7-19ae-450f-a566-1e0194287cf7.png)
