### ISSUE TITLE
don't store the sshkey if it's already there

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#88]
![store_sshkey](https://user-images.githubusercontent.com/41957921/206158461-67a3e685-b423-4768-9be5-ffb7afccb986.gif)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/89

[screen-capture.webm](https://user-images.githubusercontent.com/57001890/206165785-2ee40510-a3b7-4547-aa0c-484815b223ac.webm)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

If the ssh key is already stored it'll not get stored again every time it's loaded.

[Get Mastodon (30).webm](https://user-images.githubusercontent.com/101194226/206210661-270987a8-0592-4c07-9526-5bf6276ac292.webm)


[Untitled_ Dec 7, 2022 4_48 PM.webm](https://user-images.githubusercontent.com/101194226/206210702-bdc02e18-093c-41e5-a8da-ae3b9140219a.webm)
