### ISSUE TITLE
send background checks for the domains to make sure it's up and running

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#9]
I understand it's still booting, but better to let the user know in the instances table and show a message it's booting up
![image](https://user-images.githubusercontent.com/64129/203851335-4c1e6c5c-6fbf-4e84-9026-c546ec91e28f.png)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

After a successful deployment a warning message will appear mentioning that the user will be notified once the mastodon instance is up and running. and after about 2 min it disappeared and another message appear mentioning that `Your Mastodon Instance is up and running` and indeed i tried to access the instance after i got this message it was working without any issues and i did not get `Bad Gateway`.

[Get Mastodon (8).webm](https://user-images.githubusercontent.com/101194226/204553212-e9bc259d-9c9f-4b6b-8f7c-751c8e227a5b.webm)

However i noticed an issue where my deployment did not appear in the deployment list until i reloaded the page so i created a separate issue for it https://github.com/threefoldtech/www-mastodon/issues/41
