### ISSUE TITLE
Add a clear error message when there are no Certified nodes in the selected region

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#90]
### Description

Add a clear error message when there are no Certified nodes in the selected region instead of showing an error message in the `Select Node ID` field mentioning that `Node ID is required.` while there are no nodes to select.

[Get Mastodon (29).webm](https://user-images.githubusercontent.com/101194226/206201856-96756998-bc92-49a7-800f-2c82776bbdce.webm)

**Comment by MohamedElmdary** [comment]
## Fixed
https://github.com/threefoldtech/www-mastodon/pull/95

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

A clear error message is shown when there are no certified nodes in the selected region, and the tabs also show that there's a validation issue in it.

![image](https://user-images.githubusercontent.com/101194226/206499161-a822416c-0fdb-490c-bc11-8c7e85b1d113.png)
