### ISSUE TITLE
Add a clear error message when the entered mnemonics are not registered on the grid.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#91]
### Description 

Add a clear error message when the entered mnemonics are not registered on the grid.

For example when i entered the mnemonics of a twin that wasn't registered on mainnet i got the following message

![image](https://user-images.githubusercontent.com/101194226/206213479-c97433f0-db12-4529-93f3-d6a74b04b442.png)

A better option would be mentioning that the mnemonics are not registered on the grid and adding a link to the docs on how to activate an account, that redirects to this https://library.threefold.me/info/manual/#/getstarted/manual__dashboard_portal_polkadot_create_account or https://library.threefold.me/info/manual/#/getstarted/manual__dashboard_portal_ui_activation

or mentioning that by simply clicking on the `Create Account` button will create and activate an account for you.

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/116
