### ISSUE TITLE
`Basic` tab input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#92]
### Description 

Input validation needs to be added/revised for some fields in the `Basic` tab.

### Mastodon instance Name

- Spaces 

   ![image](https://user-images.githubusercontent.com/101194226/206217165-b218b7fb-971a-44c6-8ca5-14ef2a0be152.png)
   
   ![image](https://user-images.githubusercontent.com/101194226/206217272-44f40118-3dce-46ee-8721-35849788ccb5.png)

- Special Characters

   ![image](https://user-images.githubusercontent.com/101194226/206217522-84f3b463-9455-4249-8b9c-bffd625ae070.png)

   ![image](https://user-images.githubusercontent.com/101194226/206217598-969b5bae-9130-442f-8f5e-44b9e73d9a2c.png)

- Starts with a number

   This will not cause an error and the instance will be deployed but i think validation for it should be added for the sake of consistency with the other weblets available on the grid.

   ![image](https://user-images.githubusercontent.com/101194226/206218651-5e1c1ef5-96aa-4258-8b50-baf7ec570ef4.png)

### Admin Email

- Special characters before the `@` 
   
   ![image](https://user-images.githubusercontent.com/101194226/206219312-95475654-345e-4184-b589-fb10b58e758f.png)

   And the instance was deployed with this email and it didn't throw any validation errors after i clicked on deploy.
   
   ![image](https://user-images.githubusercontent.com/101194226/206219841-e2b84815-f20a-4b90-9b6e-7d2a7192f207.png)

### Region 

No validation messages or errors are shown when a region with no nodes is selected #20.

### Certified

No validation messages or errors are shown when there are no Certified nodes in the selected region #90.

**Comment by MohamedElmdary** [comment]
Will double check it 
I'm using [validator](https://www.npmjs.com/package/validator?activeTab=readme) so that's kinda weird behaviour
