### ISSUE TITLE
`Advanced` tab input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#93]
### Description

Input validation needs to be added/revised for some fields in the `Advanced` tab.

### Admin Username

- Spaces
   
   ![image](https://user-images.githubusercontent.com/101194226/206223508-84966247-f94a-4bbd-b9fa-8cf160347904.png)

- Special Characters

   ![image](https://user-images.githubusercontent.com/101194226/206223836-e780238f-6d21-419f-904a-c60b8d98766f.png)

- Starts with a number

   ![image](https://user-images.githubusercontent.com/101194226/206223964-47f21756-bffd-4dfe-8c65-55bc183128b1.png)

### SMTP Email

- Special character before the `@`

   ![image](https://user-images.githubusercontent.com/101194226/206225648-55edb3d2-a477-48bf-8b44-b847861b0b57.png)

**Comment by MohamedElmdary** [comment]
Same as https://github.com/threefoldtech/www-mastodon/issues/92
