### ISSUE TITLE
The `SMTP` fields are not focused on when an error is present in any of its fields.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#94]
### Description

The `SMTP` fields are not focused on when an error is present in any of its fields. 

[Get Mastodon (31).webm](https://user-images.githubusercontent.com/101194226/206226999-51feda7b-ba7c-4f43-8f9b-0ac79a045e4d.webm)

Even when you switch to another tab none of the fields will be focused on as seen in the video.

**Comment by MohamedElmdary** [comment]
Thanks for reporting @mohamedamer453

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

All of the SMTP fields are now focused on when an error is present in any of the fields.

[Get Mastodon (32).webm](https://user-images.githubusercontent.com/101194226/206505810-70dafd7c-bed5-45cd-a476-70282d5b41cd.webm)
