### ISSUE TITLE
Show pop up to allow the user to enter the solution provider ID before rendering the weblet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/www-mastodon#96]
in case of the weblet is initialized without a solution provider, show a pop-up that asks for a `code` (solution provider ID) before rendering the page. 
Also, show a message in this pop-up for how to get a code from threefold support if they don't have one

**Comment by DylanVerstraete** [comment]
We shouldn't allow a user to provide a code. A solution provider is someone who provides a solution on a certain platform. In this case, we provide the mastodon solution so the our provider ID should be filled in automatically.
